"""initial_schema

Revision ID: 588940ec7204
Revises:
Create Date: 2026-08-03 03:21:33.758889
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "588940ec7204"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_target_id"), "audit_events", ["target_id"], unique=False)
    op.create_table(
        "targets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("base_url", sa.String(length=2048), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("verify_tls", sa.Boolean(), nullable=False),
        sa.Column("collection_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("monitoring_readiness", sa.String(length=20), nullable=False),
        sa.Column("api_connection_state", sa.String(length=30), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=True),
        sa.Column("last_probe_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_collection_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_targets_next_collection_at"), "targets", ["next_collection_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "worker_heartbeats",
        sa.Column("worker_id", sa.String(length=100), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("worker_id"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("external_account_id", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("account_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("schedulable", sa.Boolean(), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("availability_reasons", sa.JSON(), nullable=False),
        sa.Column("group_ids", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rate_limit_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("overload_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("temp_unschedulable_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_observation_id", sa.String(length=36), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_id", "external_account_id", name="uq_account_target_external"),
    )
    op.create_index(op.f("ix_accounts_available"), "accounts", ["available"], unique=False)
    op.create_index(
        "ix_accounts_target_available", "accounts", ["target_id", "available"], unique=False
    )
    op.create_index(op.f("ix_accounts_target_id"), "accounts", ["target_id"], unique=False)
    op.create_table(
        "collection_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column("account_count", sa.Integer(), nullable=False),
        sa.Column("quota_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collection_runs_created_at"), "collection_runs", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_collection_runs_status"), "collection_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_collection_runs_target_id"), "collection_runs", ["target_id"], unique=False
    )
    op.create_index(
        "ix_runs_target_status_created",
        "collection_runs",
        ["target_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "collector_leases",
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=100), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("target_id"),
    )
    op.create_index(
        op.f("ix_collector_leases_lease_until"), "collector_leases", ["lease_until"], unique=False
    )
    op.create_table(
        "notification_channels",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("server_url", sa.String(length=2048), nullable=False),
        sa.Column("topic", sa.String(length=256), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("token_ciphertext", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_channels_target_id"),
        "notification_channels",
        ["target_id"],
        unique=False,
    )
    op.create_table(
        "policies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("unavailable_enabled", sa.Boolean(), nullable=False),
        sa.Column("quota_warning_remaining", sa.Float(), nullable=False),
        sa.Column("quota_critical_remaining", sa.Float(), nullable=False),
        sa.Column("quota_recovery_remaining", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_policies_target_id"), "policies", ["target_id"], unique=False)
    op.create_table(
        "quota_samples",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("external_account_id", sa.String(length=160), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("quota_key", sa.String(length=160), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("utilization_percent", sa.Float(), nullable=True),
        sa.Column("remaining_percent", sa.Float(), nullable=True),
        sa.Column("used_value", sa.Float(), nullable=True),
        sa.Column("limit_value", sa.Float(), nullable=True),
        sa.Column("remaining_value", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("freshness", sa.String(length=20), nullable=False),
        sa.Column("source_observation_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quota_samples_target_id"), "quota_samples", ["target_id"], unique=False
    )
    op.create_index(
        "ix_quota_target_account_key_time",
        "quota_samples",
        ["target_id", "external_account_id", "quota_key", "observed_at"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "target_capabilities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("scope_type", sa.String(length=20), nullable=False),
        sa.Column("scope_id", sa.String(length=160), nullable=False),
        sa.Column("support_state", sa.String(length=30), nullable=False),
        sa.Column("runtime_state", sa.String(length=30), nullable=False),
        sa.Column("freshness", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("side_effect", sa.String(length=80), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "target_id", "key", "scope_type", "scope_id", name="uq_capability_scope"
        ),
    )
    op.create_index(
        op.f("ix_target_capabilities_target_id"), "target_capabilities", ["target_id"], unique=False
    )
    op.create_table(
        "target_secrets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("auth_type", sa.String(length=30), nullable=False),
        sa.Column("ciphertext", sa.Text(), nullable=False),
        sa.Column("key_id", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_target_secrets_target_id"), "target_secrets", ["target_id"], unique=True
    )
    op.create_table(
        "account_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("producer_id", sa.String(length=100), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("external_account_id", sa.String(length=160), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("freshness", sa.String(length=20), nullable=False),
        sa.Column("runtime_state", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["collection_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("producer_id", "batch_id", "sequence", name="uq_observation_replay"),
    )
    op.create_index(
        op.f("ix_account_observations_target_id"),
        "account_observations",
        ["target_id"],
        unique=False,
    )
    op.create_index(
        "ix_observation_target_account_time",
        "account_observations",
        ["target_id", "external_account_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("policy_id", sa.String(length=36), nullable=False),
        sa.Column("subject_type", sa.String(length=30), nullable=False),
        sa.Column("subject_id", sa.String(length=160), nullable=False),
        sa.Column("rule_key", sa.String(length=100), nullable=False),
        sa.Column("window_key", sa.String(length=160), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("fired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["policy_id"], ["policies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint", name="uq_incident_fingerprint"),
    )
    op.create_index(op.f("ix_incidents_policy_id"), "incidents", ["policy_id"], unique=False)
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_index(op.f("ix_incidents_target_id"), "incidents", ["target_id"], unique=False)
    op.create_table(
        "incident_transitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("from_status", sa.String(length=30), nullable=True),
        sa.Column("to_status", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incident_transitions_incident_id"),
        "incident_transitions",
        ["incident_id"],
        unique=False,
    )
    op.create_table(
        "notification_outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=True),
        sa.Column("transition_id", sa.String(length=36), nullable=False),
        sa.Column("channel_id", sa.String(length=36), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["notification_channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transition_id", "channel_id", name="uq_outbox_transition_channel"),
    )
    op.create_index(
        op.f("ix_notification_outbox_incident_id"),
        "notification_outbox",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_outbox_status"), "notification_outbox", ["status"], unique=False
    )
    op.create_index(
        "ix_outbox_due", "notification_outbox", ["status", "next_attempt_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outbox_due", table_name="notification_outbox")
    op.drop_index(op.f("ix_notification_outbox_status"), table_name="notification_outbox")
    op.drop_index(op.f("ix_notification_outbox_incident_id"), table_name="notification_outbox")
    op.drop_table("notification_outbox")
    op.drop_index(op.f("ix_incident_transitions_incident_id"), table_name="incident_transitions")
    op.drop_table("incident_transitions")
    op.drop_index(op.f("ix_incidents_target_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_policy_id"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index("ix_observation_target_account_time", table_name="account_observations")
    op.drop_index(op.f("ix_account_observations_target_id"), table_name="account_observations")
    op.drop_table("account_observations")
    op.drop_index(op.f("ix_target_secrets_target_id"), table_name="target_secrets")
    op.drop_table("target_secrets")
    op.drop_index(op.f("ix_target_capabilities_target_id"), table_name="target_capabilities")
    op.drop_table("target_capabilities")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_quota_target_account_key_time", table_name="quota_samples")
    op.drop_index(op.f("ix_quota_samples_target_id"), table_name="quota_samples")
    op.drop_table("quota_samples")
    op.drop_index(op.f("ix_policies_target_id"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_notification_channels_target_id"), table_name="notification_channels")
    op.drop_table("notification_channels")
    op.drop_index(op.f("ix_collector_leases_lease_until"), table_name="collector_leases")
    op.drop_table("collector_leases")
    op.drop_index("ix_runs_target_status_created", table_name="collection_runs")
    op.drop_index(op.f("ix_collection_runs_target_id"), table_name="collection_runs")
    op.drop_index(op.f("ix_collection_runs_status"), table_name="collection_runs")
    op.drop_index(op.f("ix_collection_runs_created_at"), table_name="collection_runs")
    op.drop_table("collection_runs")
    op.drop_index(op.f("ix_accounts_target_id"), table_name="accounts")
    op.drop_index("ix_accounts_target_available", table_name="accounts")
    op.drop_index(op.f("ix_accounts_available"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("worker_heartbeats")
    op.drop_table("users")
    op.drop_index(op.f("ix_targets_next_collection_at"), table_name="targets")
    op.drop_table("targets")
    op.drop_index(op.f("ix_audit_events_target_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
